{% set name = "blark" %}
{% set version = "0.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/blark/blark-{{ version }}.tar.gz
  sha256: 9b6a060b810bea53b257c1d303d7a2689a54b54e225d22e4416f204db4229bee

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - blark = blark.__main__:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - lark >=1.0
    - lxml
    - packaging
    - typing-extensions

test:
  requires:
    - python {{ python_min }}
  imports:
    - blark
    - blark.tests
  commands:
    - blark --help
    - blark parse --help
    - blark format --help

about:
  home: https://github.com/klauer/blark
  license: GPL-2.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Beckhoff TwinCAT ST (IEC 61131-3) code parsing in Python using Lark

extra:
  recipe-maintainers:
    - klauer
