{% set name = "blark" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/klauer/blark/archive/v{{ version }}.tar.gz
  sha256: 3ac85981b7478196c5d4f6e65de367965632a5608e06b67850de65e7e81f924c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - blark = blark.__main__:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytmc
    - lark >=1.0

test:
  imports:
    - blark
    - blark.tests
  commands:
    - blark --help

about:
  home: https://github.com/klauer/blark
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Beckhoff TwinCAT ST (IEC 61131-3) code parsing in Python using Lark

extra:
  recipe-maintainers:
    - klauer
